

#%RAML 1.0 NamedExample
value:
  -
    eventtypeid: 33
    eventname: New Student Enrollment
    exchangename: capella.direct
    exchangetype: direct
    queuename: new.student.enrollment
    routingkey: student.2016
    headers: "{[key:value]}"
  -
    eventtypeid: 45
    eventname: New Course 2019
    exchangename: capella.fanout
    exchangetype: fanout
    queuename: new.course.2019
    routingkey: student.2016
    headers: "[{key:value}]"