#%RAML 1.0 NamedExample
value:
  eventtypeid: 33
  eventname: New Student Enrollment
  exchangename: capella.direct
  exchangetype: direct
  queuename: new.student.enrollment
  routingkey: student.2016
  headers: "{[key:value]}"