#%RAML 1.0
title: capella-event-catalog-training

types: 
  eventCatalogNoID: !include datatype/eventCatalogNoID.raml
  eventCatalog: !include datatype/eventCatalog.raml


/eventcatalog:
  get:
    description: Get list of Event Catalog
    responses: 
      200:
        body: 
          application/json:
            type: eventCatalog[]
            example: !include example/eventCatalogs.raml
  post:
    description: Add Event Catalog
    body: 
      application/json:
        type: eventCatalogNoID
        example: !include example/eventCatalogNoID.raml
    responses: 
      201:
        body: 
          application/json:
            example:
              message: "Event catalog created"
  
  /{ID}:
    get:
      description: Get individual Event Catalog
      responses: 
        200:
          body: 
            application/json:
              type: eventCatalog
              example: !include example/eventCatalog.raml
    put:
      description: Update Event Catalog by id
      body: 
        application/json:
          type: eventCatalog
          example: !include example/eventCatalog.raml
      responses: 
        200: 
          body:
            application/json:
              example:
                message: Event Catalog Successfullky Added
    patch:
      description: Update individual field on Event Catalog
      body: 
        application/json:
          type: eventCatalogNoID
          example: !include example/eventCatalogNoID.raml
          
    delete:
      description: Remove event catalog
      responses: 
        200:
          body: 
            application/json:
              example:
                Message: Event removed (Not really)
      